---
# playbook.yml
- name: Install deps
  hosts: default
  become: true
  tasks:

    - name: Get ldap-utils
      apt:
        state: latest
        name: 
          - ldap-utils
          - debconf-utils
          - libpam-ldapd
          - nslcd
          - nscd
          - nslcd-utils
          - libnss-ldapd

    - name: Install slapd
      apt:
        state: latest
        name: 
          - slapd

    - name: Start slapd
      service:
        name: slapd
        state: started
