# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.hostname = "ubuntu"
  config.vm.boot_timeout = 600

  # Disable automatic box update checking.
  config.vm.box_check_update = false

  # using a specific IP.
  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.14"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.


  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.cpus = 4
    vb.linked_clone = true
    # Customize the amount of memory on the VM:
    vb.memory = "8192"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    sudo apt install -y python3-pip
    pip install ansible
    ansible-galaxy collection install ansible.posix
    if [ ! -d "/vagrant" ]; then sudo mkdir /vagrant && sudo chmod -R 777 /vagrant; fi
  SHELL

  config.vm.provision "file", source: "playbook.yml", destination: "/vagrant/playbook.yml"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/playbook.yml"
    ansible.become = true
  end

  
 

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
