---
# playbook.yml
- name: Install client deps
  hosts: all
  become: true
  tasks:

    - name: Install dependencies
      apk:
        update_cache: yes
        state: latest
        name:
          - docker
          - go
          - git
          - openjdk17-jdk
          - apache2
          - iproute2

    - name: install docker pip
      pip:
        name: docker

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: enable apache2
      service:
        name: apache2
        enabled: yes
        state: started
    
    - name: Clone repo
      git:
        repo: 'https://github.com/grafana/docker-otel-lgtm'
        dest: /home/vagrant/docker-otel-lgtm

    - name: Add env variable to user's .bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export OTEL_EXPORTER_OTLP_ENDPOINT="http://192.168.56.16:4318"'
        create: yes