---
# playbook.yml
- name: Install client deps
  hosts: all
  become: true
  tasks:

    - name: Install docker and go
      apk:
        update_cache: yes
        state: latest
        name:
          - docker
          - go
    - name: install docker pip
      pip:
        name: docker
    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Install client web server
      apk:
        state: latest
        name: 
          - apache2
          - iproute2

    - name: enable apache2
      service:
        name: apache2
        enabled: yes
        state: started
    
    - name: Install HotROD container image
      docker_image:
        name: jaegertracing/example-hotrod
        source: pull
    
    - name: Install Telemetrygen container image
      docker_image:
        name: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen
        source: pull

    - name: Launch Telemetrygen container and send data to server 
      docker_container:
        name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen
        env: 
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://192.168.56.16:4318"
          TELEMETRYGEN_INTERVAL: "30s"
        state: started
        restart_policy: always
          
    - name: Launch HotROD container
      docker_container:
        name: hotrod
        image: jaegertracing/example-hotrod 
        env: 
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://192.168.56.16:4318"
        state: started
        ports:
          - "8080:8080"
        restart_policy: always

    - name: Enable mod_status on Apache
      apache2_module:
        name: status
        state: present
      notify:
        - restart apache2

    - name: Add Apache server status URL for Prometheus scraping
      lineinfile:
        path: /etc/apache2/apache2.conf
        line: |
          <Location "/server-status">
            SetHandler server-status
            Require host 192.168.56.16  # Monitoring server IP
          </Location>
      notify:
        - restart apache2

  handlers:
  - name: restart apache2
    service:
        name: apache2
        state: restarted