---
# playbook.yml
- name: Install supervisor deps
  hosts: all
  become: true
  tasks:

    - name: Install supervisor nagios deps
      apt:
        state: latest
        name:
          - docker.io
          - wget
          - unzip
          - ufw
          - openjdk-17-jdk

    - name: Start docker
      service:
        name: docker
        state: started

    - name: Add user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Pull otel-lgtm image
      docker_image:
        name: grafana/otel-lgtm
        source: pull  
  
    - name: Launch image if not running
      docker_container:
        name: otel-lgtm
        image: grafana/otel-lgtm
        state: started
        ports:
          - "3000:3000"
          - "4317:4317"
          - "4318:4318"
        restart_policy: always