---
# playbook.yml
- name: Install deps
  hosts: all
  become: true
  tasks:
  
      - name: Install packages
        apk:
          name: 
            - acl
            - nfs-utils
            - rpcbind
            - bind
            - unbound
            - shadow
            - dhcp
            - vlan
            - iptables
            - rsyslog
          state: present